### ISSUE TITLE
Intermittent crash during terraform plan: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by rickardgranberg** [nats-io/terraform-provider-jetstream#42]
We're seeing intermittent crashes during terraform plan with the jetstream provider. It appears to happen during the resource read phase.
It happens around 30-40% of the time and not always on line 249 in util.go, but always on one of the `d.Get(...)` calls in the `connectMgr` func

Our hcl:

```hcl
variable "jetstream_streams" {
  description = "NATS Jetstream Streams to create"
  type = map(object({
    name         = string
    max_age_days = number
    subjects     = list(string)
  }))
}

data "kubernetes_secret_v1" "root_ca" {
  metadata {
    name      = local.ca_secret_name
    namespace = var.namespace
  }
}

provider "jetstream" {
  servers         = format("%s:%d", var.ingress_host, local.nats_port)
  credential_data = var.nats_account_creds
  tls {
    ca_file_data = data.kubernetes_secret_v1.root_ca.data["ca.crt"]
  }
}

resource "jetstream_stream" "streams" {
  for_each   = var.jetstream_streams
  name       = each.value.name
  max_age    = each.value.max_age_days * 60 * 60 * 24 # Convert to seconds
  subjects   = each.value.subjects
  storage    = "file"
  replicas   = var.cluster_replicas
}

```

The terraform output:

```
╷
│ Error: Plugin did not respond
│ 
│   with jetstream_stream.streams["Stream1"],
│   on ../../modules/helm/nats/main.tf line 277, in resource "jetstream_stream" "streams":
│  277: resource "jetstream_stream" "streams" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with jetstream_stream.streams["Stream2"],
│   on ../../modules/helm/nats/main.tf line 277, in resource "jetstream_stream" "streams":
│  277: resource "jetstream_stream" "streams" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-jetstream_0.0.27 plugin:

fatal error: concurrent map writes


goroutine 131 [running]:
runtime.throw({0xf0acb0, 0x0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc00078f0f0 sp=0xc00078f0c0 pc=0x433891
runtime.mapassign_faststr(0xc000650240, 0xc000405380, {0xf0105c, 0xb})
	/usr/local/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc00078f158 sp=0xc00078f0f0 pc=0x412c5c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*DiffFieldReader).ReadField(0xc000650240, {0xc000405380, 0x1, 0x1})
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/field_reader_diff.go:80 +0x5c6 fp=0xc00078f350 sp=0xc00078f158 pc=0xc27b26
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0xc0006d7460, {0xc000405380, 0x1, 0x1}, {0xef9795, 0x3})
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/field_reader_multi.go:45 +0x1b2 fp=0xc00078f480 sp=0xc00078f350 pc=0xc2adf2
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).get(0xc000100230, {0xc000405380, 0x1, 0x1}, 0x8)
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource_data.go:534 +0x1da fp=0xc00078f580 sp=0xc00078f480 pc=0xc352ba
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).getRaw(0x45ffffffff, {0xf0105c, 0x1158318}, 0x1)
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource_data.go:128 +0xa5 fp=0xc00078f630 sp=0xc00078f580 pc=0xc32f65
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).GetOk(0x203000, {0xf0105c, 0xc00078f7d0})
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource_data.go:94 +0x38 fp=0xc00078f6e8 sp=0xc00078f630 pc=0xc32c98
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).Get(...)
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource_data.go:73
github.com/nats-io/terraform-provider-jetstream/jetstream.connectMgr.func1()
	/Users/rip/go/src/github.com/nats-io/terraform-provider-jetstream/jetstream/util.go:249 +0x76 fp=0xc00078f920 sp=0xc00078f6e8 pc=0xd14eb6
github.com/nats-io/terraform-provider-jetstream/jetstream.resourceStreamRead(0xc00081bce0, {0xdb95a0, 0xc000031b90})
	/Users/rip/go/src/github.com/nats-io/terraform-provider-jetstream/jetstream/resource_jetstream_stream.go:224 +0x162 fp=0xc00078fa20 sp=0xc00078f920 pc=0xd0e7a2
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000325ae0, 0xc00007f9f0, {0xdb95a0, 0xc000031b90})
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa fp=0xc00078fa88 sp=0xc00078fa20 pc=0xc3120a
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0006da2a8, {0xc0008420c0, 0x4b6b06}, 0xc0008420c0)
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b fp=0xc00078fb70 sp=0xc00078fa88 pc=0xc4adeb
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0xec8e60, 0xc0006da2a8}, {0x1151f90, 0xc00031c090}, 0xc000842060, 0x0)
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170 fp=0xc00078fbc8 sp=0xc00078fb70 pc=0xb95710
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ada40, {0x1162028, 0xc000134480}, 0xc000350a00, 0xc0007ceab0, 0x17e29b0, 0x0)
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f fp=0xc00078fe48 sp=0xc00078fbc8 pc=0x8530cf
google.golang.org/grpc.(*Server).handleStream(0xc0003ada40, {0x1162028, 0xc000134480}, 0xc000350a00, 0x0)
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a fp=0xc00078ff68 sp=0xc00078fe48 pc=0x856caa
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98 fp=0xc00078ffe0 sp=0xc00078ff68 pc=0x850d78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00078ffe8 sp=0xc00078ffe0 pc=0x463e41
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc00039fed0)
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/server.go:472 +0x14d3
github.com/hashicorp/terraform-plugin-sdk/plugin.Serve(0xc00039ff48)
	/Users/rip/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/plugin/serve.go:76 +0x365
main.main()
	/Users/rip/go/src/github.com/nats-io/terraform-provider-jetstream/main.go:9 +0x45

goroutine 5 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000282180)
	/Users/rip/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/Users/rip/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x92

goroutine 114 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).StartStream.func1()
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/grpc_broker.go:70 +0x10d
created by github.com/hashicorp/go-plugin.(*gRPCBrokerServer).StartStream
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/grpc_broker.go:68 +0x136

goroutine 78 [select]:
github.com/hashicorp/go-plugin.(*grpcStdioServer).StreamStdio(0xc000031280, 0xe3af40, {0x115ebf0, 0xc0000314e0})
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/grpc_stdio.go:58 +0x126
github.com/hashicorp/go-plugin/internal/plugin._GRPCStdio_StreamStdio_Handler({0xdca180, 0xc000031280}, {0x11587c8, 0xc0004a6480})
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/internal/plugin/grpc_stdio.pb.go:185 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003ada40, {0x1162028, 0xc000134480}, 0xc0006f2800, 0xc0007cea20, 0x17d9460, 0x0)
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1441 +0xcdb
google.golang.org/grpc.(*Server).handleStream(0xc0003ada40, {0x1162028, 0xc000134480}, 0xc0006f2800, 0x0)
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1521 +0x9e5
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

goroutine 32 [IO wait]:
internal/poll.runtime_pollWait(0x7f98ce9ef6d8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0006e4c80, 0x20, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0006e4c80)
	/usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc0006e4c80)
	/usr/local/go/src/net/fd_unix.go:173 +0x35
net.(*UnixListener).accept(0xc000022df0)
	/usr/local/go/src/net/unixsock_posix.go:167 +0x1c
net.(*UnixListener).Accept(0xc000794e70)
	/usr/local/go/src/net/unixsock.go:260 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc0003ada40, {0x1149378, 0xc0006d6d40})
	/Users/rip/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:720 +0x362
github.com/hashicorp/go-plugin.(*GRPCServer).Serve(0xc0005955f0, {0x1149378, 0xc0006d6d40})
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/grpc_server.go:138 +0x71
created by github.com/hashicorp/go-plugin.Serve
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/server.go:466 +0x1445

goroutine 31 [chan receive]:
github.com/hashicorp/go-plugin.Serve.func3()
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/server.go:437 +0x75
created by github.com/hashicorp/go-plugin.Serve
	/Users/rip/go/pkg/mod/github.com/hashicorp/go-plugin@v1.3.0/server.go:434 +0x1291

Error: The terraform-provider-jetstream_0.0.27 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by ripienaar** [comment]
I saw this once in the past but couldnt make it happen again, We will need to add something like here https://github.com/rporres/terraform-provider-helm/commit/eb58c2767c764b33b1a30a1bb09ad205b39a1e4f

**Comment by ripienaar** [comment]
Maybe fixed in https://github.com/nats-io/terraform-provider-jetstream/pull/43

**Comment by ripienaar** [comment]
Please try with v0.0.28
